# Workflow ini akan melakukan build dan testing terhadap development app.
name: Dev Testing 🔎 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-testing:
    name: Build and Testing
    runs-on: ubuntu-latest
    environment: Dev 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.DB_USER }}" > .env
          echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ vars.DB_DBNAME }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.DB_PORT }}" >> .env

      - name: Build and Run Container
        run: |
          sudo docker compose up database app-dev --build --detach

      - name: Hit Endpoint
        run: |
          sleep 20
          curl http://localhost:5002
          
      - name: Testing
        run: |
          python3 testing/test.py